# -*- coding: utf-8 -*-
"""Python_03_While.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bDtmTXe2ckSmsFTMXlFktUP6RLNFxgo0

# <font color='red'>Ferramenta de Automação de Processos - Python</font>

### Básico: While
"""

# Usando o loop while para imprimir os valores de 0 a 9
contador = 0
while contador < 5:
    print(contador)
    contador = contador + 1
print("Fim do programa")

# Também é possível usar a claúsula else para encerrar o loop while
x = 0

while x < 5:
    print ('O valor de x nesta iteração é: ', x)
    print (' x ainda é menor que 5, somando 1 a x')
    x += 1

else:
    print ('Loop concluído!')

"""### Pass, Break, Continue"""

contador = 0
while True:
    if contador == 4:
        break #sai do bloco
    else:
        pass
    print(contador)
    contador = contador + 1

for letra in "Laeta":
    if letra == "e":
        continue # inicia a iteração do começo
    print(letra,end='')

"""### While e For juntos"""

for i in range(2,10):
    j = 2
    contador = 0
    while j < i:
        print(i , j)
        if i % j == 0:
            contador = 1
            j = j + 1
        else:
            j = j + 1

    if contador == 0:
        print(str(i) + " é um número primo")
        contador = 0
    else:
        contador = 0

"""# Fim"""