# -*- coding: utf-8 -*-
"""Python_01_If-Elif-Else.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D1HYcsEH8Cyy6RIC9pkOz4C192ToZSq-
"""

# <font color='red'>Ferramenta de Automação de Processos - Python</font>

"""### Básico: Condicional If"""

# Condicional If
if 100 < 99:
    print("100 é maior que 99!")

# Statement If...Else
if 100 < 99:
   print("imprime se verdadeiro")
else:
   print("imprime se falso")

9 > 1

print(4 > 8)

1 < 9

10 >= 10

if 100 == 100:
  print("100 é igual a 100")

x = False
if x:
    print('Sempre !')

# Atenção com a sintaxe
if 48 > 25:
  print("Faltou o :")

# Atenção com a sintaxe
if 48 > 25:
print("agora sim !")

"""### Condicionais Aninhados"""

idade = 66
if idade > 65:
   print("Você pode aposentar!")

idade = 88
if idade > 50:
    if idade > 65:
        print("66 a Infinito")
    else:
        print("51 a 65 ")
else:
      if idade > 25:
        print("tem entre 26 e 50 anos ")
      else:
        print("0 a 25 anos")
print("Fim")

idade = 17
Nome = "Mariaaaa"
if idade >= 18 and Nome == "Maria":
    print("Ok Maria, você está autorizado a entrar!")
else:
    print("saindo")

idade = 12
Nome = "Bob"
if (idade >= 13) or (Nome == "Bob"):
    print("Ok Bob, você está autorizado a entrar!")

"""### Elif"""

dia = "Quarta"
if dia == "Domingo":
  print("Hoje fará sol!")
else:
  print("Hoje vai chover!")

if dia == "Domingo":
  print("Hoje fará sol!")
elif dia == "Quarta":
  print("Hoje vai chover!")
else:
  print("Sem previsão do tempo para o dia selecionado")

"""### Operadores Lógicos"""

idade = 18
nome = "José"
if idade > 17:
   print("Você pode dirigir!")

idade = 16
if idade > 17 and nome == "José":
   print("Autorizado!")
else:
    print("Não autorizado")

# Usando mais de uma condição na cláusula if

lab = input('Digite o nome do laboratório: ')
nome = input('Digite o nome do colaborador: ')

if lab == 'laeta' and nome == 'Nelson':
    print('Confirmado! Nelson é do Laeta!')
else:
    print('Lamento, acho que esse funcionário não trabalha nesse laboratório')

# Usando mais de uma condição na cláusula if e introduzindo Placeholders

disciplina = input('Digite o nome da disciplina(sem acento): ')
nota_final = input('Digite a nota final (entre 0 e 100): ')
semestre = input('Digite o semestre (1 a 4): ')

if disciplina == 'matematica' and nota_final >= '50' and int(semestre) != 1:
    print('Você foi aprovado em %s com média final %r!' %(disciplina, nota_final))
else:
    print('Lamento, acho que você precisa estudar mais!')

"""# Fim"""